## Compile container
FROM node:16.13.1-alpine3.14

# Install SupervisorD
RUN apk add supervisor

# --------------- ## Mirror of production file ## -------------- #

# Install packages
RUN apk add --no-cache \
  # Used for udev init script
  bash \
  # Add USB mount dependencies
  findmnt \
  grep \
  udev \
  util-linux \
  # Install NGINX and PHP-FPM
  curl \
  nginx \
  php8 \
  php8-ctype \
  php8-curl \
  php8-dom \
  php8-fpm \
  php8-gd \
  php8-intl \
  php8-json \
  php8-mbstring \
  php8-mysqli \
  php8-opcache \
  php8-openssl \
  php8-phar \
  php8-session \
  php8-xml \
  php8-xmlreader \
  php8-zlib \
  && rm /etc/nginx/http.d/default.conf

# Set application directory 
WORKDIR /app/

# Create root directories #
RUN mkdir -p public/storage && \
  mkdir -p public/interface/asset_share/assets && \
  mkdir -p public/storage/fileshare && \
  mkdir -p public/storage/library && \ 
  mkdir -p public/storage/website
    
# Configure SupervisorD
COPY config/supervisor/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Enable USB support on device
ENV UDEV=on
COPY config/usb/udev/usb.rules /etc/udev/rules.d/usb.rules
COPY config/usb/entrypoint.sh /usr/bin/
COPY config/usb/scripts /usr/src/scripts
RUN chmod +x /usr/bin/entrypoint.sh
RUN chmod +x /usr/src/scripts/*

# Configure PHP-FPM and NGINX
COPY config/php/fpm-pool.conf /etc/php8/php-fpm.d/www.conf
COPY config/php/php.ini /etc/php8/conf.d/custom.ini
COPY /config/nginx/nginx.conf /etc/nginx/nginx.conf
COPY /config/nginx/conf/ /etc/nginx/http.d/

# Insert website holding page
COPY --chown=nginx /config/nginx/assets/index.html public/storage/website/index.html
COPY --chown=nginx /config/nginx/assets/web.png public/storage/website/web.png

# --------------- ## End mirror of production file ## -------------- #

# Create dev env asset_share
RUN mkdir -p public/interface_dev/public/asset_share/assets

# Set file permissions 
RUN chown -R nginx.nginx /run && \
  chown -R nobody.nobody public/interface/asset_share/ && \
  chown -R nobody.nobody public/storage/fileshare/ && \
  chown -R nobody.nobody public/storage/library/ && \
  chown -R nobody.nobody public/storage/website/

# Disable USB support to prevent error message in dev env
ENV UDEV=off

# Overwrite default Supervisor.conf with dev version
COPY config/supervisor/supervisord_dev.conf /etc/supervisor/conf.d/supervisord.conf

# Overwrite default NGINX.conf with dev version
COPY /config/nginx/nginx.dev.conf /etc/nginx/nginx.conf

# Start services
CMD yarn install --cwd /app/public/interface_dev/ && \
  exec supervisord -c /etc/supervisor/conf.d/supervisord.conf
