# Build File Manager
FROM composer:2.0.11 AS filemanager-buildstep

# Provide TERM for TPUT
ENV TERM=xterm

# Install required build dependencies
RUN apk add ncurses

# Set workdir to the build folder
WORKDIR /build-context

# Copy content to prepare
COPY apps/file-manager/ .

# Run the build process
RUN composer run build


FROM node:14.17.0-alpine3.13

# Install SupervisorD
RUN apk add supervisor

# --------------- ## Mirror of production file ## -------------- #
# ----------- 'install_packages' switched for 'apk add' --------- #

# Add mount dependencies
RUN apk add \
  findmnt \
  grep \
  util-linux 
  
# Install Nginx and PHP-FPM
RUN apk add \
  curl \
  nginx \
  php8 \
  php8-ctype \
  php8-curl \
  php8-dom \
  php8-fpm \
  php8-gd \
  php8-intl \
  php8-json \
  php8-mbstring \
  php8-mysqli \
  php8-opcache \
  php8-openssl \
  php8-phar \
  php8-session \
  php8-xml \
  php8-xmlreader \
  php8-zlib \
  && rm /etc/nginx/conf.d/default.conf

# Install File Manager dependencies
RUN apk add \
  libbz2 \
  libzip \
  libcap \
  openldap-dev \
  php8-bz2 \
  php8-fileinfo \
  php8-ldap \
  php8-posix \
  php8-zip

# Set application directory 
WORKDIR /app/

# Create root directories #
RUN mkdir -p public/files && \
  mkdir -p public/storage && \
  mkdir -p public/storage/fileshare && \
  mkdir -p public/storage/library && \ 
  mkdir -p public/storage/website && \
  mkdir -p public/interface/lb_share/assets
    
# Configure SupervisorD
COPY config/supervisor/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Enable USB support on device
ENV UDEV=on
COPY config/usb/udev/usb.rules /etc/udev/rules.d/usb.rules
COPY config/usb/scripts /usr/src/scripts
RUN chmod +x /usr/src/scripts/*

# Configure PHP-FPM and NGINX
COPY config/php/fpm-pool.conf /etc/php8/php-fpm.d/www.conf
COPY config/php/php.ini /etc/php8/conf.d/custom.ini
COPY /config/nginx/nginx.conf /etc/nginx/nginx.conf
COPY /config/nginx/conf/ /etc/nginx/conf.d/

# Insert website holding page
COPY --chown=nginx /config/nginx/assets/index.html public/storage/website/index.html
COPY --chown=nginx /config/nginx/assets/web.png public/storage/website/web.png

# --------------- ## End mirror of production file ## -------------- #

# Copy built content ready for adding to folders
COPY --from=filemanager-buildstep /build-context/dist /filemanager/build/dist

# Create dev-env lb_share
RUN mkdir -p public/interface_dev/public/lb_share/assets

# Set file permissions 
RUN chown -R nginx.nginx /run && \
  chown -R nobody.nobody public/storage/fileshare/ && \
  chown -R nobody.nobody public/storage/library/ && \
  chown -R nobody.nobody public/storage/website/ && \
  chown -R nobody.nobody public/interface/lb_share/

# Enable Library OnDevice mode
ENV ONDEVICE=TRUE

# Disable USB support to prevent error message in dev env
ENV UDEV=off

# Overwrite default Supervisor.conf with dev version
COPY config/supervisor/supervisord_dev.conf /etc/supervisor/conf.d/supervisord.conf

# Overwrite default NGINX.conf with dev version
COPY /config/nginx/nginx.dev.conf /etc/nginx/nginx.conf

# Start services
CMD rm -rf /app/public/files/* && \
  cp -Rf /filemanager/build/dist/* /app/public/files/ && \
  yarn install --cwd /app/public/interface_dev/ && \
  yarn install --cwd /app/public/library/ && \ 
  exec supervisord -c /etc/supervisor/conf.d/supervisord.conf
