FROM node:14.16.0-alpine3.13

# Install development dependencies
RUN apk add python3
RUN yarn global add @quasar/cli && export PATH="$(yarn global bin):$PATH"

# Install SupervisorD
RUN apk add supervisor

# --------------- ## Mirror of production file ## -------------- #
# ----------- 'install_packages' switched for 'apk add' --------- #

# Add mount dependencies
RUN apk add findmnt util-linux grep

# Install Nginx and PHP-FPM
RUN apk add php7 php7-fpm php7-opcache php7-mysqli php7-json \
    php7-openssl php7-curl php7-zlib php7-xml php7-phar php7-intl php7-dom \
    php7-xmlreader php7-ctype php7-session php7-mbstring php7-gd nginx curl && \
    rm /etc/nginx/conf.d/default.conf

# Install File Manager dependencies
RUN apk add libbz2 libzip libcap openldap-dev php7-zip php7-ldap php7-bz2 \
    php7-fileinfo php7-posix

# Set application directory 
WORKDIR /app/

# Create root directories #
RUN mkdir -p public/files && \
    mkdir -p public/storage && \
    mkdir -p public/storage/fileshare && \
    mkdir -p public/storage/library && \ 
    mkdir -p public/storage/makerspace && \ 
    mkdir -p public/storage/website
    
# Configure SupervisorD
COPY config/supervisor/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Enable USB support on device
ENV UDEV=on
COPY config/usb/udev/usb.rules /etc/udev/rules.d/usb.rules
COPY config/usb/scripts /usr/src/scripts
RUN chmod +x /usr/src/scripts/*

# Configure PHP-FPM and NGINX
COPY config/php/fpm-pool.conf /etc/php7/php-fpm.d/www.conf
COPY config/php/php.ini /etc/php7/conf.d/custom.ini
COPY /config/nginx/nginx.conf /etc/nginx/nginx.conf
COPY /config/nginx/conf/ /etc/nginx/conf.d/

# Insert website holding page
COPY --chown=nginx /config/nginx/assets/index.html public/storage/website/index.html
COPY --chown=nginx /config/nginx/assets/web.png public/storage/website/web.png

# Insert File Manager source code
COPY --chown=nginx /apps/file-manager/dist public/files

# Insert Library source code
COPY --chown=nginx /apps/library/dist/spa public/library

# Insert interface source code
COPY --chown=nginx /apps/interface/dist/spa public/interface

# Set file permissions 
RUN chown -R nginx.nginx /run && \
    chown -R nobody.nobody public/storage/fileshare/ && \
    chown -R nobody.nobody public/storage/library/ && \
    chown -R nobody.nobody public/storage/makerspace/ && \
    chown -R nobody.nobody public/storage/website/

# --------------- ## End mirror of production file ## -------------- #

# Enable Library OnDevice mode
ENV ONDEVICE=TRUE

# Disable USB support to prevent error message in dev env
ENV UDEV=off

# Overwrite default Supervisor.conf with dev version
COPY config/supervisor/supervisord_dev.conf /etc/supervisor/conf.d/supervisord.conf

# Overwrite default NGINX.conf with dev version
COPY /config/nginx/nginx.dev.conf /etc/nginx/nginx.conf

# Start services
CMD yarn install --cwd /app/public/interface_dev/ && \
    yarn install --cwd /app/public/library/ && \ 
    supervisord -c /etc/supervisor/conf.d/supervisord.conf
