# Build File Manager
FROM composer:2.0.11 AS filemanager-buildstep

# Install required build dependencies
RUN apk add ncurses

# Set workdir to the build folder
WORKDIR /build-context

# Copy content to prepare
COPY apps/file-manager/ .

# Run the build process
RUN composer run build


FROM alpine:3.13

# Copy built content ready for adding to folders
COPY --from=filemanager-buildstep /build-context/dist /build/filemanager

# On start of the container, copy the content into the mounted directoies
CMD rm -rf /export/filemanager/* && \
  cp -Rf /build/* /export/ && \  
  echo "Build complete and files added to directories. Check the logs above for build errors."
