FROM balenalib/amd64-alpine-node:14-build

## Install development dependencies
RUN apk add python3
RUN yarn global add @quasar/cli && export PATH="$(yarn global bin):$PATH"


# --------------- ## Mirror of production file ## -------------- #
# Install packages #

## Install SupervisorD
RUN apk add supervisor

## Add mount dependencies
RUN install_packages findmnt util-linux grep

## Install Nginx and PhP-FPM
RUN install_packages php7 php7-fpm php7-opcache php7-mysqli php7-json \
    php7-openssl php7-curl php7-zlib php7-xml php7-phar php7-intl php7-dom \
    php7-xmlreader php7-ctype php7-session php7-mbstring php7-gd nginx curl && \
    rm /etc/nginx/conf.d/default.conf

## Install File Manager dependencies
RUN install_packages libbz2 libzip libcap openldap-dev php7-zip php7-ldap php7-bz2 \
    php7-fileinfo php7-posix


# Create root directories #
RUN mkdir -p /app/web/public/frontend && \
    mkdir -p /app/web/public/files && \
    mkdir -p /app/web/public/storage && \
    mkdir -p /app/web/public/storage/library && \ 
    mkdir -p /app/web/public/storage/website && \
    mkdir -p /app/web/public/storage/fileshare

# Set application directory 
WORKDIR /app/web/

# Configure the controller #

## Configure SupervisorD
COPY config/supervisor/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

## Enable USB support on device
ENV UDEV=on
COPY config/usb/udev/usb.rules /etc/udev/rules.d/usb.rules
COPY config/usb/scripts /usr/src/scripts
RUN chmod +x /usr/src/scripts/*

# Configure PhP-FPM and NGINX
COPY config/php/fpm-pool.conf /etc/php7/php-fpm.d/www.conf
COPY config/php/php.ini /etc/php7/conf.d/custom.ini
COPY /config/nginx/nginx.conf /etc/nginx/nginx.conf
COPY /config/nginx/conf/ /etc/nginx/conf.d/

## Set file permissions 
RUN chown -R nginx.nginx /run && \
    chown -R nginx.nginx /app/web/public/frontend && \
    chown -R nobody.nobody /app/web/public/storage/library/ && \
    chown -R nobody.nobody /app/web/public/storage/website/ && \
    chown -R nobody.nobody /app/web/public/storage/fileshare/

# --------------- ## End mirror of production file ## -------------- #

## Disable USB support to prevent error message in dev env
ENV UDEV=off

# Overwrite default Supervisor.conf with dev version
COPY config/supervisor/supervisord_dev.conf /etc/supervisor/conf.d/supervisord.conf

# Start services
CMD yarn install --cwd /app/web/public/interface_dev/ && supervisord -c /etc/supervisor/conf.d/supervisord.conf
