version: '3.4'

services:
    wifi_connect:
        build:
            context: ./controller
            dockerfile: Dockerfile.dev.wifi
        stdin_open: true
        ports: 
            - "8080:8080"
        labels:
            portainer: hidden
        volumes:
            - './controller/apps/wifi-connect/ui:/app/wifi-connect/ui:cached'
            - 'yarn_cache_wifi:/usr/local/share/.cache/yarn/'

volumes:
    yarn_cache_wifi:
