version: '2.1'

services:
    controller:
        build:
            context: ./controller
            dockerfile: Dockerfile.template
        restart: always
        network_mode: "host"
        volumes:
            - 'portainer_data:/app/portainer'
        labels:
            io.balena.features.dbus: '1'
            io.balena.features.supervisor-api: '1'
            portainer: hidden
        cap_add:
            - NET_ADMIN
        environment:
            DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"

    backend:       
        build:
            context: ./backend
            dockerfile: Dockerfile.template
        restart: always
        ports: 
            - "3001:3001"
        depends_on:
            - "controller"
        volumes:
            - 'backend_db:/app/db'
        labels:
            portainer: hidden

    frontend:       
        build:
            context: ./frontend
            dockerfile: Dockerfile.template
        restart: always
        ports:
            - "80:8081"
        volumes:
            - filestorage:/app/web/public/storage
        labels:
            portainer: hidden
        depends_on:
        - "backend"
        privileged: true

    portainer:
        build:
            context: ./portainer
        restart: on-failure
        ports:
            - '9000:9000'
        labels:
            portainer: hidden
            io.balena.features.balena-socket: '1'
        volumes:
            - 'portainer_data:/data'
        command: --admin-password=$2y$05$j4Gnyhud5p8W81VI7MCbJep1w/.ToYPn3KQEZerJNLqUaV2qKnvT.

volumes:
    filestorage:
    portainer_data:
    backend_db:
