# Ensure Docker has access to sufficient 'CPUs' and memory via the Docker 
# preferences page before running.
version: '2.1'

services:
  controller:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev.backend
    restart: on-failure
    ports: 
      - "9090:9090"
    labels:
      portainer: hidden
    depends_on:
      - "frontend"
    volumes:
      - './backend/apps/controller:/app'
      - 'file_storage:/app/storage'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'asset_share:/app/asset_share'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev.interface
    ports: 
      - "8081:8081"
    labels:
      portainer: hidden
    volumes:
      - './frontend/apps/interface:/app/public/interface_dev:cached'
      - './frontend/apps/library:/app/public/library:cached'
      - 'file_storage:/app/public/storage'            
      - 'yarn_cache_frontend:/usr/local/share/.cache/yarn/'
      - 'asset_share:/app/public/interface_dev/public/asset_share'

volumes:
  file_storage:
  asset_share:
  yarn_cache_frontend:
