version: '3.4'

services:
    build:
        build:
            context: .
            dockerfile: Dockerfile.build
        volumes:
            - './frontend/apps/file-manager/dist:/export/filemanager'
            - './frontend/apps/interface/dist/spa:/export/interface'
            - './frontend/apps/library/dist/spa:/export/library'
            - './controller/apps/wifi-connect/ui/build:/export/controller'
