version: '3.4'

services:
    wifi_connect:
        build:
            context: ./controller
            dockerfile: Dockerfile_wifi.dev
        stdin_open: true
        ports: 
            - "8080:8080"
        labels:
            portainer: hidden
        volumes:
            - './controller/wifi-connect/ui:/app/wifi-connect/ui:cached'
            - 'yarn_cache_wifi:/usr/local/share/.cache/yarn/'

    controller:
        build:
            context: ./controller
            dockerfile: Dockerfile_controller.dev
        ports: 
            - "9090:9090"
        volumes:
            - 'filestorage:/app/storage'
        labels:
            portainer: hidden
        volumes:
            - ./controller/app:/app

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        ports: 
            # Live reload Quasar interface
            - "8082:8082"
            # Orignal server via NGINX
            - "8081:8081"
        labels:
            portainer: hidden
        volumes:
            - 'filestorage:/app/web/public/storage'
            - './frontend/apps/interface:/app/web/public/interface/build/spa'
            - './frontend/apps/interface:/app/web/public/interface_dev:cached'
            - './frontend/apps/file-manager/dist:/app/web/public/files'
            - 'yarn_cache_frontend:/usr/local/share/.cache/yarn/'

volumes:
    filestorage:
    yarn_cache_frontend:
    yarn_cache_wifi:
