version: '2.1'

services:
  controller:
    build:
      context: ./backend
      dockerfile: Dockerfile.template
    restart: always
    network_mode: "host"
    volumes:
      - 'asset_share:/app/asset_share'
      - 'controller_db:/app/db'
      - 'file_storage:/app/storage'
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-socket: '1'
      portainer: hidden
    depends_on:
      - "frontend"
    cap_add:
      - NET_ADMIN
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.template
    restart: always
    ports:
      - "80:8081"
    volumes:
      - 'asset_share:/app/public/interface/asset_share'
      - 'file_storage:/app/public/storage'
    labels:
      portainer: hidden
    privileged: true # Required for USB access

volumes:
  asset_share:
  controller_db:
  file_storage:
