version: '2.1'

services:
  controller:
    build:
      context: ./controller
      dockerfile: Dockerfile.dev.backend
    restart: on-failure
    ports: 
      - "9090:9090"
    labels:
      portainer: hidden
    volumes:
      - './controller/apps/backend:/app'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'lb_share:/app/lb_share'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev.interface
    ports: 
      - "8081:8081"
    labels:
      portainer: hidden
    volumes:
      - './frontend/apps/interface:/app/public/interface_dev:cached'
      - './frontend/apps/library:/app/public/library:cached'
      - './frontend/apps/file-manager/dist:/app/public/files:cached'
      - './controller/apps/backend/storage/library:/app/public/storage/library'            
      - 'yarn_cache_frontend:/usr/local/share/.cache/yarn/'
      - 'lb_share:/app/public/interface_dev/public/lb_share'

  wifi_connect:
    build:
      context: ./controller
      dockerfile: Dockerfile.dev.wifi-connect
    stdin_open: true
    ports: 
      - "8080:8080"
    labels:
      portainer: hidden
    volumes:
      - './controller/apps/wifi-connect/ui:/app/wifi-connect/ui:cached'
      - 'yarn_cache_wifi:/usr/local/share/.cache/yarn/'

volumes:
  lb_share:
  yarn_cache_frontend:
  yarn_cache_wifi:
