version: '2.1'

services:
  controller:
    build:
      context: ./controller
      dockerfile: Dockerfile.template
    restart: always
    network_mode: "host"
    volumes:
      - 'portainer_data:/app/portainer'
      - 'controller_db:/app/db'
      - 'file_storage:/app/storage'
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-socket: '1'
      portainer: hidden
    depends_on:
      - "frontend"
    cap_add:
      - NET_ADMIN
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"

  frontend:       
    build:
      context: ./frontend
      dockerfile: Dockerfile.template
    restart: always
    ports:
      - "80:8081"
    volumes:
      - 'file_storage:/app/public/storage'
    labels:
      portainer: hidden
    privileged: true

  portainer:
    build:
      context: ./portainer
    restart: on-failure
    ports:
      - '9000:9000'
    labels:
      portainer: hidden
      io.balena.features.balena-socket: '1'
    depends_on:
      - "controller"
    volumes:
      - 'portainer_data:/data'
    command: -H unix:///var/run/balena-engine.sock --admin-password=$2y$05$j4Gnyhud5p8W81VI7MCbJep1w/.ToYPn3KQEZerJNLqUaV2qKnvT.

volumes:
  controller_db:
  file_storage:
  portainer_data:
