version: '2.1'

services:
    controller:
        build:
            context: ./controller
            dockerfile: Dockerfile.dev
        restart: always
        network_mode: "host"
        volumes:
            - 'portainer_data:/app/portainer'
        labels:
            io.balena.features.dbus: '1'
            io.balena.features.supervisor-api: '1'
            portainer: hidden
        cap_add:
            - NET_ADMIN
        environment:
            DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"

    backend:       
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        volumes:
            - ./backend/backend/server:/app/backend
        restart: always
        labels:
            portainer: hidden

    frontend:       
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        restart: always
        ports:
            - "80:8081"
        labels:
            portainer: hidden
        depends_on:
        - "controller"
        - "backend"
        privileged: true

        volumes:
            - ./frontend/apps/frontend/public:/app/web/public/frontend
            - ./frontend/apps/file-manager/dist:/app/web/public/files

    portainer:
        image: portainer/portainer-ce
        restart: on-failure
        ports:
            - '9000:9000'
        labels:
            portainer: hidden
            io.balena.features.balena-socket: '1'
        depends_on:
        - "controller"
        volumes:
            - 'portainer_data:/data'
            - '/var/run/docker.sock:/var/run/docker.sock'
        command: "--admin-password=$$2y$$05$$j4Gnyhud5p8W81VI7MCbJep1w/.ToYPn3KQEZerJNLqUaV2qKnvT."

volumes:
    portainer_data:
