FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-node:build AS buildstep

# Set node env
ENV NODE_ENV=production

# Add node app
COPY app /build-context
WORKDIR /build-context

# Add production .env
RUN mv .env.production .env

# Install app dependencies
RUN npm install

FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-node

## INSERT PACKAGES

COPY --from=buildstep build-context/ /app/

# SET APPLICATION DIRECTORY
WORKDIR /app

CMD ["node", "server.js"]
