FROM balenalib/amd64-alpine-node

# Set application directory
WORKDIR /app

# Set node env
ENV NODE_ENV=development

# Create node modules folder
RUN mkdir -p node_modules

# Create databse folder
RUN mkdir -p db

# Copy both package.json and package-lock.json to container
COPY app/package*.json ./

# Install app dependencies
RUN npm install

# Bundle app source
COPY ./app/ ./

# Expose port 
EXPOSE 3001

# Start backend dev server
CMD bash -c "npm run dev"
