FROM python:3.8.12-alpine

# Set working directory 
WORKDIR /app

RUN apk add \
  # BCrypt dependencies
  gcc \
  g++ \
  libffi-dev \
  musl-dev \
  # Natsort dependencies for more accurate sorting of files in File Manager 
  py3-icu

# Set env variables
ENV FLASK_ENV=development
ENV FLASK_APP=run
ENV PYTHONUNBUFFERED=1

# Install required packages
COPY apps/controller/requirements-dev.txt /tmp/
RUN pip install -r /tmp/requirements-dev.txt --no-cache-dir

# Launch
CMD ["sh", "start.sh"]
