FROM python:3.8.10-alpine

# Set working directory 
WORKDIR /app

RUN apk add \
  build-base \
  dbus-libs \
  dnsmasq \
  glib \
  iw \
  libffi-dev \
  musl \
  py3-icu

# Set env variables
ENV FLASK_ENV=development
ENV FLASK_APP=run
ENV PYTHONUNBUFFERED=1

# Install required packages
COPY apps/controller/requirements-dev.txt /tmp/
RUN pip install -r /tmp/requirements-dev.txt --upgrade --no-deps --force-reinstall --no-cache-dir

# Launch
CMD ["sh", "start.sh"]
