FROM balenalib/amd64-debian-python:3.8.6

## INSTALL PACKAGES

# API

COPY .env /app/
COPY requirements.txt /tmp/

RUN pip install --no-deps --no-cache-dir \
    aniso8601==8.0.0 \
    certifi==2020.6.20 \
    chardet==3.0.4 \
    click==7.1.2 \
    Flask==1.1.2 \
    Flask-RESTful==0.3.8 \
    idna==2.10 \
    itsdangerous==1.1.0 \
    Jinja2==2.11.2 \
    MarkupSafe==1.1.1 \
    python-dotenv==0.15.0 \
    pytz==2020.1 \
    requests==2.24.0 \
    six==1.15.0 \
    urllib3==1.25.10 \
    Werkzeug==1.0.1

#Dev tools
RUN install_packages nano

## BUILD WI-FI CONNECT
WORKDIR /app

## CONFIGURE WIFI-CONNECT
COPY scripts-dev .

## CONFIGURE PORTAINER
COPY portainer/portainer.db /app/portainer/portainer.db

## WRAP-UP
CMD ["python3", "start.py"]
