FROM balenalib/amd64-debian-python:3.8.6

# Set working directory 
WORKDIR /app

# Set env variables
ENV FLASK_ENV=development
ENV FLASK_APP=run

# Install required packages
COPY app-dev/requirements-dev.txt /tmp/
RUN pip install -r /tmp/requirements-dev.txt --no-deps --no-cache-dir &&

# Install dev tools
RUN install_packages nano

# Configure portainer
COPY portainer/portainer.db portainer/portainer.db

# Configure Wi-Fi connect
COPY app .

# Launch
CMD ["flask", "db", "upgrade", "&&", "python3", "run.py"]
