FROM python:3.8.6-buster

# Set working directory 
WORKDIR /app

RUN apt-get update && apt-get install -y \
  psmisc \
  rsync \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Set env variables
ENV FLASK_ENV=development
ENV FLASK_APP=run

# Install required packages
COPY apps/backend/requirements-dev.txt /tmp/
RUN pip install -r /tmp/requirements-dev.txt --upgrade --no-deps --force-reinstall --no-cache-dir

# Launch
CMD ["bash", "start.sh"]
