FROM python:3.8.6-buster

# Set working directory 
WORKDIR /app

# Set env variables
ENV FLASK_ENV=development
ENV FLASK_APP=run

# Install required packages
COPY apps/backend/requirements-dev.txt /tmp/
RUN pip install -r /tmp/requirements-dev.txt --upgrade --no-deps --force-reinstall --no-cache-dir

# Launch
CMD ["bash", "start.sh"]
