name: "Deploy Release"

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - "develop"
      - "!l10n_master"
jobs:
  deploy-release:
    name: "Deploy Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: '0'

      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set environment variables
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - if: github.ref == 'refs/heads/develop'
        name: Update .version file
        run: echo VERSION=Pre-Release > ${GITHUB_WORKSPACE}/controller/apps/backend/.version

      - if: github.ref == 'refs/heads/develop'
        name: Commit .version file
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Learner's Block
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'Update version files'
          branch: develop
          add: './controller/apps/backend/.version'

      - if: startsWith(github.ref, 'refs/tags/v')
        name: Update .version file
        run: echo VERSION="$RELEASE_VERSION" > ${GITHUB_WORKSPACE}/controller/apps/backend/.version

      - if: startsWith(github.ref, 'refs/tags/v')
        name: Commit .version file
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Learner's Block
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'Update version files'
          branch: master
          add: './controller/apps/backend/.version'

      - if: startsWith(github.ref, 'refs/tags/v')
        name: Checkout production Library from 'main' branch
        run: |
          cd ./frontend/apps/library && \
            git checkout -f main && \
            cd $GITHUB_WORKSPACE

      - name: Build Quasar and WiFi-Connect
        run: |
          docker-compose -f docker-compose.build.yml up --build

      - if: startsWith(github.ref, 'refs/tags/v')
        name: Create ZIP Package for Releases
        run: |
          tar -cz --exclude-vcs --exclude-vcs-ignores -f ../Learners-Block-Dist-$RELEASE_VERSION.tar.gz -C $GITHUB_WORKSPACE .
          mv ../Learners-Block-Dist-$RELEASE_VERSION.tar.gz $GITHUB_WORKSPACE

      - if: startsWith(github.ref, 'refs/heads/develop')
        name: Create development changeLog and publish pre-release
        uses: "marvinpinto/action-automatic-releases@v1.1.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "development"
          prerelease: true
          title: "Development Build"
          files: |
            Learners-Block-*.zip

      - if: startsWith(github.ref, 'refs/tags/v')
        name: Create production changeLog and publish releases
        uses: "marvinpinto/action-automatic-releases@v1.1.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            Learners-Block-Dist-*.tar.gz
            Learners-Block-*.zip
