name: "Deploy Development Release"
on:
 pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main
jobs:
  deploy-release:
    name: "Deploy Development Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Update versions
        run: |
          echo VERSION="dev" > ${GITHUB_WORKSPACE}/backend/apps/controller/.version && \
          echo "RELEASE_VERSION=dev" >> $GITHUB_ENV

      - name: Remove 'version' line from balena.yml in development environment
        run: sed -i '/version/,+1 d' ${GITHUB_WORKSPACE}/balena.yml

      - name: Check output
        run: |
          echo ${{ github.head_ref }}

      - if: ${{ github.head_ref }} != i10n_master
        name: Deploy aarch64 to development
        uses: balena-io/balena-ci@master
        id: build-dev-aarch64
        with:
          balena_token: ${{ secrets.BALENA_API_TOKEN }}
          fleet: learner_s_block/lb-dev-aarch64

      - if: ${{ github.head_ref }} != i10n_master
        name: Deploy armv7hf to development
        uses: balena-io/balena-ci@master
        id: build-dev-armv7hf
        with:
          balena_token: ${{ secrets.BALENA_API_TOKEN }}
          fleet: learner_s_block/lb-dev-armv7hf
