name: "Development Release"

on:
 pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main

jobs:
  balena_cloud_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: balena-io/balena-ci@master
        id: build
        with:
          balena_token: ${{ secrets.BALENA_API_TOKEN }}
          fleet: arran_magee/lb-dev
      - name: Log release ID built
        run: echo "Built release ID ${{ steps.build.outputs.release_id }}"
