name: Docker Image CI

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

defaults:
    run:
      working-directory: controller

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile.dev
