name: Docker Image CI

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

defaults:
    run:
      working-directory: controller

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile.dev -t controller
        docker run -d -p 9090:9090 controller
        sleep 10
        curl http://0.0.0.0:9090
