name: Docker Image CI

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

defaults:
    run:
      working-directory: controller

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile.dev --tag controller
        docker run controller
        docker exec -it controller sh
        sudo apt-get update
        sudo apt-get install libdbus-glib-1-dev libgirepository1.0-dev
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        printenv
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
