name: Node Lint Wi-Fi Connect

on:
  push:
    paths:
      - 'controller/apps/wifi-connect/**'
      - '!controller/apps/wifi-connect/ui/src/components/i18n/**'
  pull_request:
    paths:
      - 'controller/apps/wifi-connect/**'
      - '!controller/apps/wifi-connect/ui/src/components/i18n/**'  

defaults:
    run:
      working-directory: controller/apps/wifi-connect/ui/

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: yarn install
    - run: yarn lint
